# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: |
        npm config set TEST_DB_URL=${TEST_DB_URL}
        npm test
      env:
        TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
        COOKIE_SECRET: ${{ secrets.COOKIE_SECRET}}
    - uses: akhileshns/heroku-deploy@master
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "discussion-board-backend"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        healthcheck: "https://discussion-board-backend.herokuapp.com/posts"
      env:
        HD_TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
        HD_DB_URL: ${{ secrets.DB_URL }}
        HD_IMG_API_KEY: ${{ secrets.IMG_API_KEY }}
        HD_IMG_API_SECRET: ${{ secrets.IMG_API_SECRET }}
        HD_IMG_CLOUD_NAME: ${{ secrets.IMG_CLOUD_NAME }}
        HD_COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}

       

