# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Create Env file
      run: |
        touch .env  
        echo TEST_DB_URL=${{ secrets.TEST_DB_URL }} >> .env
        echo DB_URL=${{ secrets.DB_URL }} >> .env
        echo IMG_API_KEY=${{ secrets.IMG_API_KEY }} >> .env
        echo IMG_API_SECRET=${{ secrets.IMG_API_SECRET }} >> .env
        echo IMG_CLOUD_NAME=${{ secrets.IMG_CLOUD_NAME }} >> .env

    - name: Delete gitignore
      run: |
        rm .gitignore
    - name: Push .env to directory
      run: |
        git config user.email ${{ secrets.MY_EMAIL }}
        git config user.name  ${{ secrets.MY_USER_NAME }}
        git add .
        git commit -m "environment variables"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

